### ISSUE TITLE
夜间模式未完全适配集中反馈

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1143]
**关于哪一项功能**
夜间模式

**问题描述**
夜间模式未完全适配集中反馈。

发现两个应援团相关未完全适配的地方。

**脚本版本**
~~不写了，反正也没那么快关~~
正式版 v1.11.0

**浏览器版本**
~~不写了，反正也没那么快关~~
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 86.0.4240.111（正式版本） （64 位）

**错误信息**

**附加截图**
- [ ] 分享至应援团聊天的动态：
![image](https://user-images.githubusercontent.com/49396421/97730389-c09def00-1b0e-11eb-9ee2-932ccaebae7b.png)
- [ ] 应援团更多菜单（强迫症扣细节）：
![image](https://user-images.githubusercontent.com/49396421/97730099-60a74880-1b0e-11eb-96c5-123acc3f1edd.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 原版顶栏搜索框在夜间模式下其实有点难发现（特别是现在这个动画横幅下）
![image](https://user-images.githubusercontent.com/49396421/97944802-9c693900-1dc0-11eb-9599-3e33c4631948.png)
原版效果：
![image](https://user-images.githubusercontent.com/49396421/97944785-8fe4e080-1dc0-11eb-9293-3ceb0d94fdd5.png)
要不遵照 b 站白天原有的元素风格，比如隔壁 Bilibili Helper 适配后的样子：
![image](https://user-images.githubusercontent.com/49396421/97946156-7ba2e280-1dc4-11eb-8694-3e9796c8d974.png)

**Comment by Geeyun-JY3** [comment]
原版顶栏相关：
- [ ] 收藏
![favgif](https://user-images.githubusercontent.com/49396421/97994089-e3d2e200-1e1f-11eb-98a9-d156a0d219d6.gif)
- [ ] 历史
![historygif](https://user-images.githubusercontent.com/49396421/97993740-6effa800-1e1f-11eb-8e05-ea4d23e5d7df.gif)
- [ ] 动态面板一开始加载时未覆盖
![dynamicgif](https://user-images.githubusercontent.com/49396421/97994912-d2d6a080-1e20-11eb-970e-cb8ec99146a5.gif)
	- [ ] 动态面板的 `专栏动态` tab：鼠标飘过文章时无相应暗示（既没有像现在 `视频动态` tab 下鼠标飘过文章时题目变为主题色的暗示，也没有白天原有风格的暗示。建议遵照 b 站白天原有的元素风格）
![cvgif](https://user-images.githubusercontent.com/49396421/97995083-0adde380-1e21-11eb-9a5a-d5115c092115.gif)

**Comment by Geeyun-JY3** [comment]
番剧详情页的面包屑导航：
![image](https://user-images.githubusercontent.com/49396421/98129846-92e0ed80-1ef4-11eb-968b-4bb0530e657c.png)

> ps: 如果这个面包屑导航够长，其实还有两个翻页用的按钮：
![image](https://user-images.githubusercontent.com/49396421/98128159-86f42c00-1ef2-11eb-9276-480c67715d3b.png)

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/pull/1137#issuecomment-719540484 and @LonelySteve in https://github.com/the1812/Bilibili-Evolved/pull/1137#issuecomment-719564138_
（伪

**Comment by Geeyun-JY3** [comment]
- [ ] 番剧播放页的 `分享到动态` 对话框：
![image](https://user-images.githubusercontent.com/49396421/98208844-f876bd80-1f78-11eb-8416-174f636b4669.png)

**Comment by Geeyun-JY3** [comment]
好家伙，能在除番剧放映厅外的任意视频记笔记了

- [ ] 目前这里没适配的地方有：很明显的记笔记面板：
![image](https://user-images.githubusercontent.com/49396421/98209060-455a9400-1f79-11eb-99e8-172754e2bb39.png)

- [ ] 普通视频页面视频菜单中的 `记笔记` 按钮不跟随主题色
![image](https://user-images.githubusercontent.com/49396421/98209128-5efbdb80-1f79-11eb-9477-9cfd1bd59078.png)

**Comment by Geeyun-JY3** [comment]
优化建议：点评文字输入框遵照 b 站白天原有的元素风格，扩大些
![cvgif](https://user-images.githubusercontent.com/49396421/98362632-8ed5dc80-2068-11eb-84d5-a67c2e0be361.gif)

**Comment by Geeyun-JY3** [comment]
- [ ] 任意新闻公告下（如：https://link.bilibili.com/p/eden/news#/newsdetail?id=1537 ）仍然有 https://github.com/the1812/Bilibili-Evolved/issues/731#issuecomment-674881554 提到的问题：
![image](https://user-images.githubusercontent.com/49396421/98368334-23910800-2072-11eb-9ac2-c73bfdb990ab.png)

- [ ] 另外建议当鼠标悬停在下图的五个子 tab（直播、小视频、相簿 tab 下都有）下时中间文字跟随主题色，遵照 b 站白天原有的元素风格。
![image](https://user-images.githubusercontent.com/49396421/98367289-576b2e00-2070-11eb-83c6-85c2ab12c9fb.png)
b 站白天原有的元素风格：
![image](https://user-images.githubusercontent.com/49396421/98367515-bcbf1f00-2070-11eb-92ed-884f4754d668.png)

- [ ] （强迫症抠细节）鼠标悬停在新闻公告页下的这四个图标时中间图标变白，遵照 b 站白天原有的元素风格。
要是更严谨地遵照 b 站白天原有的元素风格，建议在无鼠标经过时也显示外围的圆。
![bl](https://user-images.githubusercontent.com/49396421/98368799-e4af8200-2072-11eb-96c0-9adf4e044cb6.gif)

**Comment by Geeyun-JY3** [comment]
- [ ] [网络诊断页](https://www.bilibili.com/blackboard/diagnostics.html)
![image](https://user-images.githubusercontent.com/49396421/98463942-32a2c200-21fa-11eb-8551-56626f382ce2.png)

- [ ] [关于bilibili新版播放页的使用说明书](https://www.bilibili.com/blackboard/activity-webplayer_.html) 扣个小细节：让文中超链接在夜间模式下显示为主题色
![image](https://user-images.githubusercontent.com/49396421/98464109-7fd36380-21fb-11eb-903c-cb4df8575004.png)

**Comment by Geeyun-JY3** [comment]
[排行榜](https://www.bilibili.com/v/popular/rank/all) 鼠标悬停在 UP 主上时未跟随主题色（应该是最近刚改的）
![image](https://user-images.githubusercontent.com/49396421/98527322-d7360a00-22b5-11eb-9a82-d1600a7734f3.png)

**Comment by Geeyun-JY3** [comment]
- [ ] [直播日历](https://live.bilibili.com/p/html/live-web-calendar/) 是之前没做还是 b 站改了这里：
![image](https://user-images.githubusercontent.com/49396421/98541300-2f770700-22ca-11eb-9551-decc4d1ce1ca.png)
![image](https://user-images.githubusercontent.com/49396421/98541407-5fbea580-22ca-11eb-8394-4f2aa7533776.png)

**Comment by Geeyun-JY3** [comment]
- [ ] [直播个人中心 > 我的直播间 > 开播设置](https://link.bilibili.com/p/center/index#/my-room/start-live) 的这个「直播推广」未跟随主题色：
![image](https://user-images.githubusercontent.com/49396421/98929732-883adf80-2516-11eb-9c6c-878083be536c.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 番剧／放映厅播放页点赞按钮偏暗、未跟随主题色
![image](https://user-images.githubusercontent.com/49396421/99102303-db955680-2618-11eb-940f-1a9ecae11f87.gif)

**Comment by Geeyun-JY3** [comment]
- [ ] 鼠标靠近但未悬停在选集列表切换按钮时颜色不匹配主题色，应该和跟 https://github.com/the1812/Bilibili-Evolved/pull/1145#issue-513397450 提到的动态关注栏翻页箭头类似
![copylink](https://user-images.githubusercontent.com/49396421/99148025-67ae8900-26c0-11eb-84cb-1ea2e7fc7417.gif)

**Comment by Geeyun-JY3** [comment]
- [ ] [放映厅](https://www.bilibili.com/cinema/)、[电影](https://www.bilibili.com/movie/)、[电视剧](https://www.bilibili.com/tv/)、[纪录片](https://www.bilibili.com/documentary/) 页的返回顶部按钮，目测和 [番剧、国创页的返回顶部按钮](https://github.com/the1812/Bilibili-Evolved/issues/731#issuecomment-695803597) 是一批人做的：
![image](https://user-images.githubusercontent.com/49396421/99149122-15bd3180-26c7-11eb-8ba3-d22577de0c03.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 索引页（[番剧索引](https://www.bilibili.com/anime/index/)、[国产动画索引](https://www.bilibili.com/guochuang/index/)、[电影索引](https://www.bilibili.com/movie/index/)、[电视剧索引](https://www.bilibili.com/tv/index/)）筛选指示箭头为矩形
![image](https://user-images.githubusercontent.com/49396421/99149455-18208b00-26c9-11eb-93ac-50695231457e.png)

**Comment by Geeyun-JY3** [comment]
改版后的宽屏模式下创作团队 UP 主头像右下角的关注按钮：
![image](https://user-images.githubusercontent.com/49396421/99274083-d6c4e280-2864-11eb-8bf8-c52e9f6f4cc9.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 直播特定分区横幅区域多处未跟随主题色：
  - [ ] ![image](https://user-images.githubusercontent.com/49396421/99348302-3f977380-28d4-11eb-8675-055c6bd35736.png)
  - [ ] ![image](https://user-images.githubusercontent.com/49396421/99348407-79687a00-28d4-11eb-92d5-3a2e40b56ae8.png)

附：b 站白天原有风格参考：
![image](https://user-images.githubusercontent.com/49396421/99348360-62c22300-28d4-11eb-931d-ad3f2bff2df1.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 直播间主播荣誉 tab 下过多时左右翻页按钮
![image](https://user-images.githubusercontent.com/49396421/99372134-bba4b200-28fa-11eb-8fe2-0243833ead49.png)

- [ ] 未登录状态下直播间弹幕输入框
![image](https://user-images.githubusercontent.com/49396421/99371792-551f9400-28fa-11eb-8a76-e14f9c7ee515.png)

**Comment by LonelySteve** [comment]
> 改版后的宽屏模式下创作团队 UP 主头像右下角的关注按钮：

这个关注按钮应该是跟随主题色的把，如果只有 UP 一个人的话，那个关注按钮就是跟随主题色的

**Comment by Geeyun-JY3** [comment]
> 那个关注按钮就是跟随主题色的

重点不是跟随主题色，看图，是这些关注按钮在宽屏模式下是圆形套了个矩形
![image](https://user-images.githubusercontent.com/49396421/99395669-b9068480-291b-11eb-82e5-b1a093c338a4.png)

**Comment by LonelySteve** [comment]
> > 那个关注按钮就是跟随主题色的
> 
> 重点不是跟随主题色，看图，是这些关注按钮在宽屏模式下是圆形套了个矩形

嗯，我知道，这其实是误伤，那看来就算不是宽屏模式这块也有问题了：

![image](https://user-images.githubusercontent.com/34429322/99396425-b0fb1480-291c-11eb-9f19-aa7e31cc6fb2.png)

**Comment by Geeyun-JY3** [comment]
> 这其实是误伤，那看来就算不是宽屏模式这块也有问题了

我倒是无所谓这个关注按钮是什么颜色。不过你说的确实有道理，确实应该保持一致，到时候就一起改了吧。

**Comment by Geeyun-JY3** [comment]
- [ ] 个人空间 > 我的订阅 > 追番／追剧 tab > 筛选下拉菜单：鼠标经过选项时文字跟随主题色：
![dropdown2](https://user-images.githubusercontent.com/49396421/99400125-90818900-2921-11eb-8af4-5fdb88cf4f4b.gif)
遵照 b 站白天原有的元素风格：
![dropdown1](https://user-images.githubusercontent.com/49396421/99400140-94151000-2921-11eb-9a01-b51da2dcdd6f.gif)

**Comment by Geeyun-JY3** [comment]
- [ ] 活动页的 `分享到动态` 对话框夜间模式下比白天更大，也没有圆角。不知道 #1201 对 [`分享到动态` 对话框的适配](https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-722189129) 对活动页的这个对话框有没有影响
![popup](https://user-images.githubusercontent.com/49396421/99406654-1bb24d00-2929-11eb-92a5-28d8ba160de4.gif)
附 b 站白天原有风格参考：
![image](https://user-images.githubusercontent.com/49396421/99405450-bd389f00-2927-11eb-93ae-6a6ccb3dee52.png)

**Comment by Geeyun-JY3** [comment]
- [x] 已结束投票最多人投票选项跟随主题色：https://www.bilibili.com/video/av499948056/#reply3608174449
      ![image](https://user-images.githubusercontent.com/49396421/99526833-d3516880-29d6-11eb-8d4d-def20677086e.png)
      客户端深色模式效果：
      ![image](https://user-images.githubusercontent.com/49396421/99527797-5a531080-29d8-11eb-8786-4b155165b8c4.png)
      附 b 站白天原有风格参考：
![image](https://user-images.githubusercontent.com/49396421/99526803-c2a0f280-29d6-11eb-8ef1-2aee0b9e037b.png)

- [x] 使用动态卡片的动态，鼠标悬停装扮卡片文字时未跟随主题色：https://t.bilibili.com/418377952631283178
![image](https://user-images.githubusercontent.com/49396421/99528109-bf0e6b00-29d8-11eb-8d06-778f2babbd74.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 个人空间收藏夹相关：
	- [ ] 相簿收藏夹更多菜单的 `取消收藏`（这个元素风格看着和其他收藏夹的不一样，估计又不是一拨人做的，居然还是在同一个页面。b 站前端真乱）
![image](https://user-images.githubusercontent.com/49396421/99624227-d432da80-2a68-11eb-8fdd-1df9e103991f.png)
	- [ ] 课程收藏夹课程名称
![image](https://user-images.githubusercontent.com/49396421/99623936-27f0f400-2a68-11eb-9695-40906a1d289d.png)

**Comment by LonelySteve** [comment]
- [ ] 评论区视频 AV/BV 号现在会转换成相应的标题进行显示，并且会在前面添加一个蓝色的播放键图标，目前该图标未跟随主题色
  ![image](https://user-images.githubusercontent.com/34429322/99772427-bbe4bd80-2b45-11eb-9893-ebd1dc2724b4.png)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/555#issuecomment-730266650
专栏也会转换，也有一个图标。
本来想迟些再发的，因为看上去这功能好像还没做完🤣（对说的就是专栏

**Comment by Geeyun-JY3** [comment]
- [ ] 引导关注卡片跟随主题色
	- [ ] 旧版，只有一个关注按钮
![image](https://user-images.githubusercontent.com/49396421/99872337-1f411f00-2c1c-11eb-8f85-42562284bffa.png)
	- [ ] 好像刚出来个新的，还能可以直接点赞投币收藏和三连（投币还是直接投两个，不带确认的那种）
![image](https://user-images.githubusercontent.com/49396421/99872317-f456cb00-2c1b-11eb-9c56-e4b1f85676ec.png)
![image](https://user-images.githubusercontent.com/49396421/99872238-5d8a0e80-2c1b-11eb-9281-605990eb1d6a.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 大会员用户个人空间动态 tab 下的用户昵称不是粉色
![image](https://user-images.githubusercontent.com/49396421/99876548-4c98c780-2c32-11eb-82ff-b79fcc443857.png)

**Comment by Geeyun-JY3** [comment]
楼中楼的表情脸色不太对😂（预览离线版，应该是适配 https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-730962260 的时候没注意，相信很快会修复，单纯觉得有些生草所以想记录一下）：
![image](https://user-images.githubusercontent.com/49396421/100233734-19717380-2f65-11eb-8dc8-1b5184a16f68.png)
![image](https://user-images.githubusercontent.com/49396421/100233320-8afcf200-2f64-11eb-96ec-be6b44ff5433.png)
![image](https://user-images.githubusercontent.com/49396421/100233504-cbf50680-2f64-11eb-8a7c-fdc09f2af59c.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 个人空间课程 tab：
![image](https://user-images.githubusercontent.com/49396421/100530665-b6673180-322f-11eb-9d8e-be0be6b83148.png)

**Comment by TANGJunPro** [comment]
黑暗模式下，滚动条能否回归正常模式，现在滚动条太细了

**Comment by the1812** [comment]
@TANGJunPro 试试这个? https://github.com/the1812/Bilibili-Evolved/issues/484

**Comment by Geeyun-JY3** [comment]
- [ ] 原版顶栏的这个投稿按钮未跟随主题色
![image](https://user-images.githubusercontent.com/49396421/100738085-0bfa3480-3410-11eb-9018-84ed3dab608e.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 投票下方的两个复选框勾选时颜色都是绿的（未跟随主题色）
![image](https://user-images.githubusercontent.com/49396421/100750699-618b0d00-3421-11eb-96b5-0c8e13cea88e.png)

**Comment by Geeyun-JY3** [comment]
- [ ] [音乐PLUS](https://www.bilibili.com/v/musicplus/) 页小问题：
![image](https://user-images.githubusercontent.com/49396421/101146539-1279ed80-3656-11eb-8cb9-e6d2f053e757.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 稿件投诉弹窗少了一行字：`你觉得这个稿件有什么问题？`
![image](https://user-images.githubusercontent.com/49396421/101149339-c2048f00-3659-11eb-8255-7cc5e0cf18ae.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 直播间礼物面板上的两个 tab
![image](https://user-images.githubusercontent.com/49396421/101179422-22f58c80-3685-11eb-8381-01871c547e9c.png)

**Comment by Geeyun-JY3** [comment]
联动 https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-729633841
- [x] 居然还有个分享会员购商品的动态……：https://t.bilibili.com/453769445220243392
![image](https://user-images.githubusercontent.com/49396421/101242804-bd61d880-3736-11eb-9d09-e99c3106d8b0.png)

**Comment by LonelySteve** [comment]
> 联动 [#1143 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-729633841)
> 
> * [ ]  居然还有个分享会员购商品的动态……：
>   ![image](https://user-images.githubusercontent.com/49396421/101242804-bd61d880-3736-11eb-9d09-e99c3106d8b0.png)

我在 0affaa246268f26d3c297ef6f568c57ef3c5b259 里偷了个懒，直接把那块样式挪出来了

所以像这种卡片的标题都会带上主题色了 (/▽＼)

**Comment by Geeyun-JY3** [comment]
> 所以像这种卡片的标题都会带上主题色了 (/▽＼)

猛地发现还有个活动卡片，你不说我可能还会接着发

**Comment by Geeyun-JY3** [comment]
- [ ] 部分视频下方的活动横幅的文字看不到
[av800525115](https://www.bilibili.com/video/av800525115)（可能是由于横幅中文字只有部分加粗，基本上可以确认是已结束的活动横幅才有此问题）
    ![image](https://user-images.githubusercontent.com/49396421/128491221-9cb64c18-2184-40c8-9aee-423a872da929.png)
    神奇的是，部分进行中活动横幅并无此问题：
    ![image](https://user-images.githubusercontent.com/49396421/128491343-6b3c2d1e-14f8-48df-8dca-91d04a85e61c.png)

    <details>
    <summary>已过时截图</summary>

    ![image](https://user-images.githubusercontent.com/49396421/101245532-7f6db000-3748-11eb-9369-80db21309332.png)
    ![image](https://user-images.githubusercontent.com/49396421/101245376-69abbb00-3747-11eb-8626-e8b01a465b81.png)

    </details>

    ***

    <details>
    <summary>好像已过时</summary>

    2020-12-08 补充：

    - [ ] 专栏下的活动横幅好像全部阵亡（包含活动横幅的专栏文章可以去 [哔哩哔哩专栏官号](https://space.bilibili.com/144900177) 里去找）
    ![image](https://user-images.githubusercontent.com/49396421/101497471-fa7fd200-39a5-11eb-904b-a9e2313eb26a.png)

    </details>

    ***

    2023-05-20 编辑：目前仅旧版播放页还有此问题，新版播放页已无此问题：

    - 旧版播放页：
      ![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/2664e1ef-1114-4c6d-a763-40da4c58d166)
    - 新版播放页：
      ![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/4fdc6faf-4b36-454a-b148-3b4a8db8a2a9)

**Comment by Geeyun-JY3** [comment]
- [ ] 个人空间投稿 tab 相簿分栏又改了……
![image](https://user-images.githubusercontent.com/49396421/101245671-500b7300-3749-11eb-889d-f19ffe5cfe64.png)

**Comment by Geeyun-JY3** [comment]
智能姬的登录操作通知，可能和本 issue 一开始提到的应援团聊天是类似的：
![image](https://user-images.githubusercontent.com/49396421/101351465-97ba0800-38cb-11eb-8170-9d7814c426f1.png)
![image](https://user-images.githubusercontent.com/49396421/101351530-ad2f3200-38cb-11eb-96a4-82f92b68d293.png)

**Comment by RingingVolcano** [comment]
夜间模式下 消息的操作登录通知 字体颜色会有一点点问题
https://message.bilibili.com/#/whisper
我的信息 哔哩哔哩智能姬 操作登录通知
