### ISSUE TITLE
夜间模式未完全适配继续集中反馈

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1289]
**关于哪一项功能**
夜间模式

**问题描述**
夜间模式未完全适配继续集中反馈。

发现活动列表页的返回顶部按钮有些问题。
视频下方标签弹窗建议。

**脚本版本**
~~不写了，反正前面两个 issue 都还没 close~~
正式版 v1.11.5
预览离线版 v874.16

**浏览器版本**
~~不写了，反正前面两个 issue 都还没 close~~
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 87.0.4280.88（正式版本） （64 位）

**附加截图**
Checklist:
- [ ] 活动列表页的返回顶部按钮
![gif](https://user-images.githubusercontent.com/49396421/101501981-5d279c80-39ab-11eb-86d1-1472a36bbafd.gif)
- [ ] 按 https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-728819402 的思路，鼠标悬停标签后出来的弹出的这几个按钮建议跟随主题色：
![image](https://user-images.githubusercontent.com/49396421/101503277-e5f30800-39ac-11eb-825c-b0f237eed525.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 原版顶栏两处
	- [ ] 未登录状态下登录按钮外边框还是蓝色
![image](https://user-images.githubusercontent.com/49396421/101607412-8c87e900-3a3f-11eb-9b9a-d41c67b774c1.png)
	- [ ] 漫画弹窗夜间模式下多了一块
![gif](https://user-images.githubusercontent.com/49396421/101608815-28662480-3a41-11eb-97e5-e63d49762ba4.gif)
原版效果：
![gif](https://user-images.githubusercontent.com/49396421/101608895-46cc2000-3a41-11eb-9cc9-daeaea688de1.gif)

**Comment by the1812** [comment]
多了一块的我会修复的, 要慢慢记录下这些可以透明背景的iframe

**Comment by Geeyun-JY3** [comment]
- [ ] 赛事页除赛事首页外的所有 tab（太多了，不截图了）

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/pull/1145#issuecomment-731600209 : 排行除排行榜的三个 tab 的返回顶部按钮

**Comment by Geeyun-JY3** [comment]
- [ ] 不知道是不是亲儿子才有的待遇：https://www.bilibili.com/video/av843109319?t=44s
![image](https://user-images.githubusercontent.com/49396421/102220327-9e73fb00-3f1b-11eb-9d86-fca0a1d8af7b.png)

**Comment by zbodo** [comment]
直播页突然大变样了 https://live.bilibili.com/92613
 ![image](https://user-images.githubusercontent.com/39948021/102336773-97f18c00-3fcc-11eb-80b6-4aa561c84008.png)

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/102337645-b60bbc00-3fcd-11eb-9f9a-b04a5da772d7.png)

**Comment by zbodo** [comment]
今天白的更多了😅…… https://live.bilibili.com/7114215 
![image](https://user-images.githubusercontent.com/39948021/102479473-e91b8180-4099-11eb-80fd-48d7d3b78e5f.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 我的关注 > 全部关注 右上方又多了个搜索框：
![image](https://user-images.githubusercontent.com/49396421/102612672-1e909f80-416c-11eb-9f03-380bff58d14f.png)

**Comment by Lijingze2019** [comment]
![image](https://user-images.githubusercontent.com/52600662/102629168-bea6f280-4185-11eb-80f9-aa83a1b0646c.png)
未适配

**Comment by Geeyun-JY3** [comment]
> ![image](https://user-images.githubusercontent.com/52600662/102629168-bea6f280-4185-11eb-80f9-aa83a1b0646c.png)
> 未适配

这个既然创作中心里要做的应该就是排除。
之前也跟你说过了夜间已经放弃创作中心：https://github.com/the1812/Bilibili-Evolved/issues/759#issuecomment-664268233

**Comment by Geeyun-JY3** [comment]
- [ ] 搜索首页用方向键 <kbd>↑</kbd><kbd>↓</kbd> 选择中热搜榜结果时未覆盖。好像需清空搜索历史才能看见（这个页面 B 站是不是都给忘了，搜索栏下方三个按钮都没改过来）
![image](https://user-images.githubusercontent.com/49396421/102779452-34ea6580-43cf-11eb-832c-7ff5fbb551c0.png)

- [ ] 这种番剧列表有封面图的详细展现样式（文字后面的深色背景去掉，同时鼠标悬停时分集标题变为主题色，而不是加个深色背景）
![image](https://user-images.githubusercontent.com/49396421/102781268-5d279380-43d2-11eb-90b6-d6c6c72c59fa.png)
白天效果
![image](https://user-images.githubusercontent.com/49396421/102782461-58fc7580-43d4-11eb-9ce2-f8288155714c.png)
	- [ ] 另外是否有必要在分集标题颜色深浅上和白天效果一样区分点击和没点击过的分集，或者可以一起做了。
	白天效果（目前开了夜间分集的标题颜色深浅是没差的）：
![image](https://user-images.githubusercontent.com/49396421/102782711-c3151a80-43d4-11eb-9883-8ceead4b0e08.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 动态详情页发表动态按钮出来的对话框
![image](https://user-images.githubusercontent.com/49396421/102793045-45f1a180-43e4-11eb-9060-77656122031c.png)
- [ ] 迷你播放器下方多了个进度条（跟随主题色）
![image](https://user-images.githubusercontent.com/49396421/102792758-e5fafb00-43e3-11eb-9e28-474b443d9871.png)

**Comment by CKylinMC** [comment]
个人关注页面的搜索框
![image](https://user-images.githubusercontent.com/11648014/102892751-4c8f2000-449b-11eb-82ed-3cf9d5b56331.png)

**Comment by Geeyun-JY3** [comment]
@CKylinMC 重复：https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-748051083
而且昨天已经 merge 了修复的 PR，最新的预览离线版已经没这问题了：https://github.com/the1812/Bilibili-Evolved/issues/1289#ref-commit-73b7a9d

**Comment by CKylinMC** [comment]
> @CKylinMC 重复：[#1289 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-748051083)
> 而且昨天已经 merge 了修复的 PR，最新的预览离线版已经没这问题了：[#1289 (reference)](https://github.com/the1812/Bilibili-Evolved/issues/1289#ref-commit-73b7a9d)

好吧，懒得来回切换版本了，等一波更新吧。

**Comment by Geeyun-JY3** [comment]
@CKylinMC 反馈前可以先看看 https://github.com/the1812/Bilibili-Evolved/issues/1289#issue-759540666 有没有提到，我会定时汇总，修了的我会隐藏。

**Comment by Geeyun-JY3** [comment]
- [ ] 收藏夹失效页（随便找个收藏夹后面加个 `/p1` 就能复现，如：https://www.bilibili.com/medialist/play/ml338926432/BV1TJ411C7An/p1 ）
![image](https://user-images.githubusercontent.com/49396421/103169996-a2890c80-487b-11eb-800a-faeae432dc30.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 直播间右偏下收起来的这个菜单按钮夜间模式下看不见
![image](https://user-images.githubusercontent.com/49396421/103280778-2c67df80-4a0c-11eb-91f5-fe6956b4bf6c.png)
![gif](https://user-images.githubusercontent.com/49396421/103280932-89fc2c00-4a0c-11eb-8981-1e32702646e3.gif)

**Comment by the1812** [comment]
> * [ ]  直播间右偏下收起来的这个菜单按钮夜间模式下看不见

这个菜单是我写的(
当时夜间背景随手就弄了个跟后面一样的颜色

**Comment by jacknyy** [comment]
![Snipaste_2020-12-29_21-01-01](https://user-images.githubusercontent.com/29568890/103285406-08f76180-4a19-11eb-88dc-2e494b1df960.png)


电影页面布局更新，请求适配

**Comment by Geeyun-JY3** [comment]
@jacknyy 啊你既然已经开了 #1198 就不用在这边也说了一次了。打上了 tag 就说明会处理的：https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> Bug 反馈不一定会做出回复, 特别是内容写得非常清晰时, 我就会直接加上相应的标签 (`bug` 或 `feature-request`), 表示我将会处理.

**Comment by Geeyun-JY3** [comment]
- [ ] 自定义顶栏的游戏中心有下图情况正常吗（和 https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-741638603 有点像，不知道和自定义顶栏有没有关系）
![image](https://user-images.githubusercontent.com/49396421/103451361-35073100-4cfe-11eb-9eb0-efa49a94f83c.png)
- [ ] 顺便建议鼠标悬停自定义顶栏的漫画栏目能和游戏中心一样调出原版的组件

**Comment by whyjxz14** [comment]
Bilibili Evolved (Preview Offline) | 892.96
-- | --
开启夜间模式计划时段后，设置里显示已经启用夜间模式，但实际未生效

**Comment by Geeyun-JY3** [comment]
- [ ] 收藏夹搜索框
![image](https://user-images.githubusercontent.com/49396421/103477014-8d6d2a00-4df5-11eb-8d2c-45001cf964e2.png

**Comment by Geeyun-JY3** [comment]
- [ ] 又是大会员昵称颜色问题：
番剧播放页下承包榜的大会员昵称颜色又不是粉的：
![gif](https://user-images.githubusercontent.com/49396421/103612977-90d0f480-4f60-11eb-91a1-6f94cad5dee7.gif)
番剧详情页也是，不过是从第二行开始昵称不是粉色（https://github.com/the1812/Bilibili-Evolved/pull/1137#issuecomment-719540484 截图的时候都没留意，现在的情况和第一张 GIF 是一样的）

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-749034491 忘说了，动态详情页发表动态按钮出来的对话框下面这一排按钮（除表情和参与话题）的操作菜单都得适配，参考动态首页
![image](https://user-images.githubusercontent.com/49396421/103666277-635f6780-4faf-11eb-8ca7-625a76454d9f.png)
- [ ] [番剧索引页](https://www.bilibili.com/anime/index)、番剧播放页系列封面 badge 的会员限定色变成主题色：https://github.com/the1812/Bilibili-Evolved/issues/731#issuecomment-719939475
![image](https://user-images.githubusercontent.com/49396421/103665679-a967fb80-4fae-11eb-8bcc-922ae126b5b7.png)
![image](https://user-images.githubusercontent.com/49396421/103665744-c0a6e900-4fae-11eb-9f6d-7f01ab76f8b2.png)

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-739257894 适配优化建议：相簿这个横条其实是不是应该和外面的背景色一致，和周围相比深一些（至少投稿里的视频的横条是这么做的）
![image](https://user-images.githubusercontent.com/49396421/103775563-2d7eb980-5069-11eb-9edf-c5967a922ba9.png)

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/issues/1316#issuecomment-755309853_

**Comment by Geeyun-JY3** [comment]
- [ ] 动态详情页顶栏的消息的下拉菜单
![image](https://user-images.githubusercontent.com/49396421/104830521-d605f800-5877-11eb-94f7-1c067ebc8b70.png)

**Comment by Lijingze2019** [comment]
> > ![image](https://user-images.githubusercontent.com/52600662/102629168-bea6f280-4185-11eb-80f9-aa83a1b0646c.png)
> > 未适配
> 
> @Lijingze2019 这个在创作中心里要做的应该就是排除。
> 之前也跟你说过了夜间已经放弃创作中心：[#759 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/759#issuecomment-664268233)

所以还没排除呢吗？

**Comment by Geeyun-JY3** [comment]
> 所以还没排除呢吗？

这里可能不是简单的排除就能解决的了。老实说我也不大清楚🌚。但你这问题应该确实是没修

**Comment by Geeyun-JY3** [comment]
- [ ] 应该是 #1316 修 https://github.com/the1812/Bilibili-Evolved/issues/1269#issuecomment-738775848 时引进的 bug：合集类页面下的推荐视频的标题文字，不需要光标悬停视频标题附近就跟随主题色了
![image](https://user-images.githubusercontent.com/49396421/104837492-d641da00-58ef-11eb-9a55-99716119f4c7.png)

**Comment by the1812** [comment]
> > 所以还没排除呢吗？
> 
> 这里可能不是简单的排除就能解决的了。老实说我也不大清楚🌚。但你这问题应该确实是没修
> 
> 得问问 @the1812

还没吧, 现在没法测到这个页面

**Comment by Geeyun-JY3** [comment]
> ![image](https://user-images.githubusercontent.com/52600662/102629168-bea6f280-4185-11eb-80f9-aa83a1b0646c.png)
> 未适配

这是嵌套了一个视频播放页在里面？

**Comment by LonelySteve** [comment]
[动态页](https://t.bilibili.com/482318475086157743)链接图标未适配主题色：

**Comment by LonelySteve** [comment]
播放器的字幕添加入口按钮悬浮色未适配主题色：
![image](https://user-images.githubusercontent.com/34429322/105574524-388f5480-5da0-11eb-901c-1f4b54a00362.png)
其实这同时也是复现 @Lijingze2019 问题的入口（

**Comment by Geeyun-JY3** [comment]
- [ ] 经 #1493 提醒，原版顶栏 > 历史 > 直播的这个 `直播中` badge 是不是该跟随主题色
![image](https://user-images.githubusercontent.com/49396421/105620405-b8b4c900-5e37-11eb-996b-0458aaed03b4.png)

说到这我还想问一下，在白天是天蓝色和粉色的地方是否都应跟随主题色？比如这里，白天 `直播中` badge 是粉色的，当前所在 tab（图中为 `直播历史`）是天蓝色的
不跟随的地方我知道的有大会员昵称、番剧的 `会员抢先`、`会员独享`、`独家` badge

**Comment by the1812** [comment]
这个因人而异吧, 之前没有规定过
按照我自己写夜间的风格, 是会把蓝色和粉色转为主题色, 大会员不变, 原本就是彩色/多种颜色的不变, 特殊颜色例如一些警告类的橘色 icon 也是不变的

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/discussions/1332#discussioncomment-306337 : 最近新出的视频内的投票弹窗（这是投票后的效果，已选的那个选项外面那个圈已经跟随了主题色）
![image](https://user-images.githubusercontent.com/49396421/105634254-1e38a200-5e98-11eb-8fe4-2c6b9b1d2976.png)
测试：https://www.bilibili.com/video/av373871938?start_progress=232407

- [ ] 说起来关联视频弹幕和UP主头像弹幕（改过，不再是 https://www.bilibili.com/read/cv7728299/ 里的样子）跟随主题色是不是给忘了
![image](https://user-images.githubusercontent.com/49396421/105939793-d16dea80-6094-11eb-862a-7ff23a096b4f.png)
![image](https://user-images.githubusercontent.com/49396421/105939689-ac797780-6094-11eb-99b1-2d971964382a.png)

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/106863363-5f844980-6703-11eb-887b-5ae00ab745c2.png)
[页面地址](https://www.bilibili.com/festival/2021bnj?bvid=BV1jt4y1678G) 
Preview v1.11.16
内容包: d171201

好像没看到有人提到。

**Comment by LonelySteve** [comment]
@CKylinMC 

其实目前预览版已经修过了（ 07f70d7b3c6197c976e8b0e8b5ac8af5736a0fa1 ），至于为啥还是白色背景，可能是因为热更新还没跟上吧（

我昨天晚上发现后就马上赶着发了个 PR #1525，但是忘了先 fetch 了，没想到 @Coulomb-G 已经把评论区的背景色修了，但是其实页面上还有些位置（比如分享和记笔记按钮）样式冲突了。

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/107113250-b4a59400-6898-11eb-9819-a0c6eb4e6f69.png)

已关注不应该是强调色吧
Preview v1.11.16
内容包: bae2d84

**Comment by Geeyun-JY3** [comment]
@CKylinMC 这些小细节我其实发现了不少，但懒得整理截图发出来了🌚（

**Comment by Geeyun-JY3** [comment]
- [ ] 搜索结果页集数较多的番剧和影视的分集导航：
怕适配不全给两个最典型~~长的要命~~的例子：
- 番剧：[名侦探柯南](https://search.bilibili.com/bangumi?keyword=名侦探柯南)
- 影视：[外来媳妇本地郎](https://search.bilibili.com/pgc?keyword=外来媳妇本地郎)
![image](https://user-images.githubusercontent.com/49396421/109003611-9e923300-76e2-11eb-8623-cadd91e10f97.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 删除评论对话框
![image](https://user-images.githubusercontent.com/49396421/111056579-086c5400-84bb-11eb-97cb-e7bc9d958af0.png)

**Comment by Geeyun-JY3** [comment]
- [ ] 合集页面的投币对话框
![image](https://user-images.githubusercontent.com/49396421/111058510-06f65800-84ca-11eb-8a02-ed0f20313e30.png)

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/pull/1145#issue-513397450 提到的 [404 页面](https://www.bilibili.com/404) 顶部图片好像要重新适配了
顺便提醒同在 #1145 最后提到的排行榜页面返回顶部按钮：https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-743515593

**Comment by Geeyun-JY3** [comment]
- [ ] https://github.com/the1812/Bilibili-Evolved/pull/1145#issue-513397450 提到的 [404 页面](https://www.bilibili.com/404) 顶部图片好像要重新适配了
顺便提醒同在 #1145 最后提到的排行榜页面返回顶部按钮：https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-743515593

**Comment by Geeyun-JY3** [comment]
- [ ] 居然还有番剧里有互动视频的……第一次打开番剧里的互动视频弹出的对话框要设配，如 [「女武神的餐桌」新春SP](https://www.bilibili.com/bangumi/play/ep385091)。
![image](https://user-images.githubusercontent.com/49396421/111853374-bc575e80-8955-11eb-85d5-97eb910550d0.png)
普通互动视频的对话框我试了很多次都调不出来，也就不知道适配失效了没有。
***
本 issue 至此结束，我们下个 issue 见<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">

**Comment by rainpenber** [comment]
视频笔记独立专栏页面和编辑框提示栏

笔记独立页面：https://www.bilibili.com/read/cv14246189 
提示框进入方法：在任意视频投稿处点击笔记按钮，点击公开笔记将笔记公开，发布成功后编辑器内会显示这个提示
![编辑器提示按钮6](https://user-images.githubusercontent.com/15974476/144305214-38c228f7-5081-4be8-9786-9403492c8cf6.png)

![笔记专栏页面](https://user-images.githubusercontent.com/15974476/144304920-56a55a5f-9651-4ec1-9e7f-9129e3150164.png)

**Comment by Geeyun-JY3** [comment]
@rainpenber 不太建议发在这个 issue 下，因为你也能看到这里有够多的跟评了，进来会卡卡的。要发的话建议发  到最新 #2136 下。

另外笔记专栏之前其实有提过：https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-886213606

**Comment by rainpenber** [comment]
> @rainpenber 不太建议发在这个 issue 下，因为你也能看到这里有够多的跟评了，进来会卡卡的。要发的话建议发  到最新 #2136 下。
> 
> 另外笔记专栏之前其实有提过：#2263、https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-886213606

my bad 浏览器搜索了一遍关键词没弹提示我以为没有人提过
